export declare const ERROR_CODES: {
    readonly VALIDATION_ERROR: "VALIDATION_ERROR";
    readonly AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR";
    readonly AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR";
    readonly TOKEN_EXPIRED: "TOKEN_EXPIRED";
    readonly TOKEN_REVOKED: "TOKEN_REVOKED";
    readonly TOKEN_REUSE_DETECTED: "TOKEN_REUSE_DETECTED";
    readonly INVALID_CREDENTIALS: "INVALID_CREDENTIALS";
    readonly ACCOUNT_LOCKED: "ACCOUNT_LOCKED";
    readonly EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED";
    readonly MFA_REQUIRED: "MFA_REQUIRED";
    readonly NOT_FOUND: "NOT_FOUND";
    readonly CONFLICT: "CONFLICT";
    readonly RATE_LIMITED: "RATE_LIMITED";
    readonly OAUTH_ERROR: "OAUTH_ERROR";
    readonly OAUTH_PROVIDER_ERROR: "OAUTH_PROVIDER_ERROR";
    readonly OAUTH_ACCOUNT_LINKED: "OAUTH_ACCOUNT_LINKED";
    readonly OAUTH_ACCOUNT_NOT_LINKED: "OAUTH_ACCOUNT_NOT_LINKED";
    readonly MFA_INVALID_CODE: "MFA_INVALID_CODE";
    readonly MFA_INVALID_BACKUP_CODE: "MFA_INVALID_BACKUP_CODE";
    readonly MFA_NOT_ENABLED: "MFA_NOT_ENABLED";
    readonly MFA_ALREADY_ENABLED: "MFA_ALREADY_ENABLED";
    readonly WEBAUTHN_REGISTRATION_FAILED: "WEBAUTHN_REGISTRATION_FAILED";
    readonly WEBAUTHN_AUTHENTICATION_FAILED: "WEBAUTHN_AUTHENTICATION_FAILED";
    readonly SESSION_EXPIRED: "SESSION_EXPIRED";
    readonly SESSION_REVOKED: "SESSION_REVOKED";
    readonly SESSION_NOT_FOUND: "SESSION_NOT_FOUND";
    readonly USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS";
    readonly USER_NOT_FOUND: "USER_NOT_FOUND";
    readonly USER_DELETED: "USER_DELETED";
    readonly ORGANIZATION_NOT_FOUND: "ORGANIZATION_NOT_FOUND";
    readonly ORGANIZATION_SLUG_TAKEN: "ORGANIZATION_SLUG_TAKEN";
    readonly MEMBERSHIP_NOT_FOUND: "MEMBERSHIP_NOT_FOUND";
    readonly MEMBERSHIP_ALREADY_EXISTS: "MEMBERSHIP_ALREADY_EXISTS";
    readonly CANNOT_REMOVE_OWNER: "CANNOT_REMOVE_OWNER";
    readonly CANNOT_LEAVE_ORG: "CANNOT_LEAVE_ORG";
    readonly ROLE_NOT_FOUND: "ROLE_NOT_FOUND";
    readonly PERMISSION_NOT_FOUND: "PERMISSION_NOT_FOUND";
    readonly INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS";
    readonly API_KEY_NOT_FOUND: "API_KEY_NOT_FOUND";
    readonly API_KEY_EXPIRED: "API_KEY_EXPIRED";
    readonly API_KEY_REVOKED: "API_KEY_REVOKED";
    readonly WEBHOOK_NOT_FOUND: "WEBHOOK_NOT_FOUND";
    readonly WEBHOOK_DELIVERY_FAILED: "WEBHOOK_DELIVERY_FAILED";
    readonly EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED";
    readonly EMAIL_TEMPLATE_NOT_FOUND: "EMAIL_TEMPLATE_NOT_FOUND";
    readonly VERIFICATION_TOKEN_INVALID: "VERIFICATION_TOKEN_INVALID";
    readonly VERIFICATION_TOKEN_EXPIRED: "VERIFICATION_TOKEN_EXPIRED";
    readonly VERIFICATION_TOKEN_USED: "VERIFICATION_TOKEN_USED";
    readonly PASSWORD_TOO_WEAK: "PASSWORD_TOO_WEAK";
    readonly PASSWORD_REUSED: "PASSWORD_REUSED";
    readonly PASSWORD_RESET_TOKEN_INVALID: "PASSWORD_RESET_TOKEN_INVALID";
    readonly PASSWORD_RESET_TOKEN_EXPIRED: "PASSWORD_RESET_TOKEN_EXPIRED";
    readonly INTERNAL_ERROR: "INTERNAL_ERROR";
    readonly DATABASE_ERROR: "DATABASE_ERROR";
    readonly REDIS_ERROR: "REDIS_ERROR";
    readonly ENCRYPTION_ERROR: "ENCRYPTION_ERROR";
    readonly CONFIGURATION_ERROR: "CONFIGURATION_ERROR";
};
export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
export declare const EVENT_TYPES: {
    readonly 'user.register': "user.register";
    readonly 'user.login': "user.login";
    readonly 'user.logout': "user.logout";
    readonly 'user.logout_all': "user.logout_all";
    readonly 'user.profile_update': "user.profile_update";
    readonly 'user.email_change': "user.email_change";
    readonly 'user.email_verified': "user.email_verified";
    readonly 'user.password_change': "user.password_change";
    readonly 'user.password_reset': "user.password_reset";
    readonly 'user.delete': "user.delete";
    readonly 'user.lock': "user.lock";
    readonly 'user.unlock': "user.unlock";
    readonly 'session.create': "session.create";
    readonly 'session.refresh': "session.refresh";
    readonly 'session.revoke': "session.revoke";
    readonly 'session.revoke_all': "session.revoke_all";
    readonly 'session.reuse_detected': "session.reuse_detected";
    readonly 'mfa.totp.enable': "mfa.totp.enable";
    readonly 'mfa.totp.disable': "mfa.totp.disable";
    readonly 'mfa.webauthn.register': "mfa.webauthn.register";
    readonly 'mfa.webauthn.authenticate': "mfa.webauthn.authenticate";
    readonly 'mfa.backup_codes.generate': "mfa.backup_codes.generate";
    readonly 'mfa.backup_codes.use': "mfa.backup_codes.use";
    readonly 'oauth.link': "oauth.link";
    readonly 'oauth.unlink': "oauth.unlink";
    readonly 'oauth.login': "oauth.login";
    readonly 'organization.create': "organization.create";
    readonly 'organization.update': "organization.update";
    readonly 'organization.delete': "organization.delete";
    readonly 'organization.member.invite': "organization.member.invite";
    readonly 'organization.member.add': "organization.member.add";
    readonly 'organization.member.remove': "organization.member.remove";
    readonly 'organization.member.role_change': "organization.member.role_change";
    readonly 'organization.domain.verify': "organization.domain.verify";
    readonly 'api_key.create': "api_key.create";
    readonly 'api_key.revoke': "api_key.revoke";
    readonly 'api_key.use': "api_key.use";
    readonly 'admin.user.impersonate': "admin.user.impersonate";
    readonly 'admin.user.update': "admin.user.update";
    readonly 'admin.user.delete': "admin.user.delete";
};
export type EventType = typeof EVENT_TYPES[keyof typeof EVENT_TYPES];
export declare const JWT_CLAIMS: {
    readonly ISSUER: "iss";
    readonly SUBJECT: "sub";
    readonly AUDIENCE: "aud";
    readonly EXPIRATION: "exp";
    readonly ISSUED_AT: "iat";
    readonly JWT_ID: "jti";
    readonly SESSION_ID: "sid";
    readonly EMAIL: "email";
    readonly EMAIL_VERIFIED: "email_verified";
    readonly ROLES: "roles";
    readonly PERMISSIONS: "permissions";
    readonly ORG_ID: "org_id";
    readonly MFA_VERIFIED: "mfa_verified";
};
export declare const TOKEN_DEFAULTS: {
    readonly ACCESS_TOKEN_TTL: 900;
    readonly REFRESH_TOKEN_TTL: 2592000;
    readonly VERIFICATION_TOKEN_TTL: 3600;
    readonly PASSWORD_RESET_TOKEN_TTL: 3600;
    readonly MAGIC_LINK_TOKEN_TTL: 900;
    readonly API_KEY_PREFIX_LENGTH: 8;
    readonly BACKUP_CODE_COUNT: 10;
    readonly BACKUP_CODE_LENGTH: 8;
};
export declare const RATE_LIMIT_DEFAULTS: {
    readonly LOGIN_MAX: 5;
    readonly LOGIN_WINDOW: 900;
    readonly REGISTER_MAX: 3;
    readonly REGISTER_WINDOW: 3600;
    readonly REFRESH_MAX: 10;
    readonly REFRESH_WINDOW: 60;
    readonly MFA_MAX: 5;
    readonly MFA_WINDOW: 300;
    readonly OAUTH_MAX: 10;
    readonly OAUTH_WINDOW: 300;
    readonly PASSWORD_RESET_MAX: 3;
    readonly PASSWORD_RESET_WINDOW: 3600;
    readonly EMAIL_VERIFICATION_MAX: 5;
    readonly EMAIL_VERIFICATION_WINDOW: 3600;
};
export declare const MFA_DEFAULTS: {
    readonly TOTP_ISSUER: "AuthCore";
    readonly TOTP_DIGITS: 6;
    readonly TOTP_PERIOD: 30;
    readonly WEBAUTHN_RP_NAME: "AuthCore";
    readonly WEBAUTHN_TIMEOUT: 60000;
};
export declare const PASSWORD_DEFAULTS: {
    readonly MIN_LENGTH: 8;
    readonly MAX_LENGTH: 128;
    readonly REQUIRE_UPPERCASE: true;
    readonly REQUIRE_LOWERCASE: true;
    readonly REQUIRE_NUMBER: true;
    readonly REQUIRE_SYMBOL: true;
    readonly MIN_ZXCVBN_SCORE: 3;
    readonly HISTORY_COUNT: 5;
};
export declare const SESSION_DEFAULTS: {
    readonly MAX_CONCURRENT_SESSIONS: 10;
    readonly DEVICE_FINGERPRINT_ENABLED: true;
    readonly IP_BINDING_ENABLED: false;
    readonly TRUSTED_DEVICE_TTL: 2592000;
};
export declare const OAUTH_PROVIDERS: {
    readonly GOOGLE: "google";
    readonly GITHUB: "github";
    readonly MICROSOFT: "microsoft";
    readonly GITLAB: "gitlab";
};
export type OAuthProvider = typeof OAUTH_PROVIDERS[keyof typeof OAUTH_PROVIDERS];
export declare const USER_STATUS: {
    readonly ACTIVE: "active";
    readonly LOCKED: "locked";
    readonly DELETED: "deleted";
    readonly PENDING_VERIFICATION: "pending_verification";
};
export type UserStatus = typeof USER_STATUS[keyof typeof USER_STATUS];
export declare const SESSION_STATUS: {
    readonly ACTIVE: "active";
    readonly REVOKED: "revoked";
    readonly EXPIRED: "expired";
};
export type SessionStatus = typeof SESSION_STATUS[keyof typeof SESSION_STATUS];
export declare const WEBHOOK_DELIVERY_STATUS: {
    readonly PENDING: "pending";
    readonly DELIVERED: "delivered";
    readonly FAILED: "failed";
};
export type WebhookDeliveryStatus = typeof WEBHOOK_DELIVERY_STATUS[keyof typeof WEBHOOK_DELIVERY_STATUS];
export declare const AUDIT_RISK_SCORE: {
    readonly LOW: 0;
    readonly MEDIUM: 50;
    readonly HIGH: 75;
    readonly CRITICAL: 90;
};
export declare const METADATA_VISIBILITY: {
    readonly PUBLIC: "public";
    readonly PRIVATE: "private";
    readonly UNSAFE: "unsafe";
};
export type MetadataVisibility = typeof METADATA_VISIBILITY[keyof typeof METADATA_VISIBILITY];
export declare const HTTP_STATUS: {
    readonly OK: 200;
    readonly CREATED: 201;
    readonly NO_CONTENT: 204;
    readonly BAD_REQUEST: 400;
    readonly UNAUTHORIZED: 401;
    readonly FORBIDDEN: 403;
    readonly NOT_FOUND: 404;
    readonly CONFLICT: 409;
    readonly UNPROCESSABLE_ENTITY: 422;
    readonly TOO_MANY_REQUESTS: 429;
    readonly INTERNAL_SERVER_ERROR: 500;
    readonly SERVICE_UNAVAILABLE: 503;
};
//# sourceMappingURL=index.d.ts.map